### ISSUE TITLE
URL Pattern for Deployed Routing

### ISSUE THREAD

**Issue by Quinn-Donnelly** [revaturelabs/caliber-2-meta#72]
For routing on the infrastrucutre api calls should have the following pattern.

`{BASE_URL}`/{SERVICE}/_________

The base URL will point to the ALB for the application. The service will allow the ALB to know which microservice it needs to route the request to.

To allow for this in development you should use zuul to mirror the behavior of the ALB. For reference look at the [Caliber Zuul]() repository to see how it was done for that project.

The next change is on the microservice end making sure that all routes start with the service name the best was is with this configuration in the bootstrap.yml

```
spring:
  application:
    name: category-service 
  cloud:
    config:
      name: category-service
      discovery:
        service-id: config
        enabled: true

server:
  servlet-path: /category/*
```

This is the part of the file above that would add the context path to the servlet and thus every route. Then you will just need to ensure that the pathing in the controllers doesn't also add the service name. 
```
server:
  servlet-path: /category/*
```

Finally update the frontend services to ensure that the api calls are matching the backend routes.
